### ISSUE TITLE
Allow text alignments (rtl, center, justify)

### ISSUE THREAD

**Issue by fbessadok** [daviferreira/medium-editor#126]
It would be very useful

**Comment by nmielnik** [comment]
`justifyLeft` `justifyCenter` `justifyRight` and `justifyFull` are now built-in buttons you can use.

**Comment by fbessadok** [comment]
Awesome. thanks!

**Comment by evazzadeh** [comment]
Please set a shortcut key for alignment

**Comment by j0k3r** [comment]
@evazzadeh which one should we use ?

**Comment by evazzadeh** [comment]
Common editor like mce use below shortcut key for alignments
* Align Right = Alt + Shift + r
* Align Left = Alt + Shift + l
* Align Center = Alt + Shift + c 
* Justify = Alt + Shift + j

Also for other function like set heading, create a list, insert a quote or link , ... can set shortcut for better usability.

and another note for remove alignment style on 2nd click on button. For example after set align center if we want to remove this align, we must add remove formatting button on toolbar. You can set 2nd click on align button to remove style of it.

**Comment by j0k3r** [comment]
For the moment, shortcuts are only available with one letter. I mean <kbd>CTRL</kbd>+<kbd>B</kbd> for bold. I see that Medium use the <kbd>CTRL</kbd>+<kbd>E</kbd> to align center.

We can think about adding complex shortcuts in the future to handle alignement.

**Comment by evazzadeh** [comment]
@j0k3r One letter shortcut reserved for browsers, for example Ctrl+R for redirect or Ctrl+E in chrome and IE inserts a question mark at the start of the address and in Firefox set focus to search box.

I suggest that using 2nd click on the same alignment item for removing style of it like a bold style or heading

**Comment by celloman** [comment]
Has anyone ever found a way to get 2nd click on a justify item to remove the style?

**Comment by BlackLight** [comment]
Is there any reason why, 6 years later, there's still **no freaking way** to align text in Medium - outside the smelly `document.execCommand` JS hack?

Is there any reason why a professional blogging platform like Medium believes that text alignment is not a key feature of a text editor?

Is there any reason why there's no official workaround and no official answer?

I'm speechless both because of the lack of such a fundamental feature in a text editor and the lack of an official answer by Medium 6 years after this issue was reported.

**Comment by celloman** [comment]
@BlackLight this repository isn't for a package actually used in Medium, it is just an editor based off of Medium's own proprietary editor.
