### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by alec-c4** [daviferreira/medium-editor#26]
Will be nice to add ability to produce markdown output :)

**Comment by santiagopoli** [comment]
**+1**

**Comment by zh-daniel-huang** [comment]
+1

**Comment by marjinal1st** [comment]
+1

**Comment by IonicaBizau** [comment]
I released [**Medium Editor Markdwon**](https://github.com/IonicaBizau/medium-editor-markdown), an extension that adds Markdown support.

[![](https://camo.githubusercontent.com/03766a87a00d7edd4167f1977ae337dbd0704c07/687474703a2f2f692e696d6775722e636f6d2f743174615759302e6a7067)]((https://github.com/IonicaBizau/medium-editor-markdown))

Now it would be very simple to have instead of a `pre` element, a `textarea` which will convert markdown to HTML using `marked` or so.

**Comment by daviferreira** [comment]
Awesome stuff :+1: 

Could you create a PR here and add your repo to the README?

**Comment by IonicaBizau** [comment]
@daviferreira I thought that it would be good to add it, but I guessed I spammed you enough already. :smile: PRed #406.

**Comment by daviferreira** [comment]
@IonicaBizau nah, don't worry about it. Great work!
