### ISSUE TITLE
Question: Disable <p>, use <br> instead

### ISSUE THREAD

**Issue by nspyke** [daviferreira/medium-editor#356]
Is it possible to stop the generation of paragraph tags and use line breaks instead?
If so, how? 

eg:
```
<p>Hello world</p>
<p>My name is Bob!</p>
```
becomes
```
Hello world<br><br>
My name is Bob!
```
whitespace is not important

It's a project requirement, paragraphs are not supported by the API.

**Comment by nspyke** [comment]
Closing as I no longer require an answer. I changed to another editor.

**Comment by rafasashi** [comment]
An answer would be much appreciated here thanks :)

**Comment by nmielnik** [comment]
@nspyke @rafasashi as a user, you can hold <kbd>SHIFT</kbd> when pressing <kbd>ENTER</kbd> and it should insert `<br>` instead of new `<p>` tags.  

As far as making the default behavior to insert `<br>` tags instead of `<p>` tags, this has been discussed many times in a lot of different issues.  Check out #70 for the oldest running issue that discusses this functionality.  #70 also links to all of the other issues that were created around this functionality.

In the spirit of trying to keep everything centralized, please add any other thoughts/comments into the other issue.  Thanks!
