### ISSUE TITLE
The demo seems to be broken

### ISSUE THREAD

**Issue by kostia** [daviferreira/medium-editor#395]
Hello,

The demo of the editor seems to be broken. At least no editor appears when selecting text.

Kind regards.
Kostia

**Comment by hellocosmin** [comment]
Works fine here Kostia, what browser? Tested in Chrome/Firefox on Windows. Did you check the console?

**Comment by kostia** [comment]
I tried Chrome Version 40.0.2214.94 (64-bit) on OSX and got following errors:

```
Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure stylesheet 'http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:8 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure stylesheet 'http://dfimg.com/medium-editor/dist/css/medium-editor.css'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:9 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure stylesheet 'http://dfimg.com/medium-editor/dist/css/themes/default.css'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure script 'http://dfimg.com/medium-editor/dist/js/medium-editor.js'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:34 Uncaught ReferenceError: MediumEditor is not defined
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-black-webfont.woff'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-black-webfont.ttf'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-regular-webfont.woff'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-regular-webfont.ttf'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-black-webfont.woff'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-black-webfont.ttf'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-regular-webfont.woff'. This request has been blocked; the content must be served over HTTPS.
daviferreira.github.io/:1 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-regular-webfont.ttf'. This request has been blocked; the content must be served over HTTPS.
(program):2 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-black-webfont.woff'. This request has been blocked; the content must be served over HTTPS.
(program):2 Mixed Content: The page at 'https://daviferreira.github.io/medium-editor/' was loaded over HTTPS, but requested an insecure font 'http://dfimg.com/fonts/proximanova-black-webfont.ttf'. This request has been blocked; the content must be served over HTTPS.
```

It works in Firefox.

**Comment by nchase** [comment]
@kostia check this out – this might be the way you have Chrome configured: http://malektips.com/google-chrome-ssl-mixed-content.html#.VNI33FXF9sU

by default, Chrome loads mixed content, but you can set it to block insecure content on secure pages.

**Comment by kostia** [comment]
Hmmm... It really seems to be a problem with my browser.
Thanks for the help!

**Comment by MommyMoo** [comment]
I use windows 7 Home Ed.  64-bit.  I have been able to view my google font in the local but not on FireFox or Chrome.  My herokuapp DID WORK on an LG android tablet I own and it worked when my prof opened it on his Mac.  

The fixes that worked for me:

FOR FIREFOX: I got it to work in FireFox by opening my herokuapp in FireFox, going into the settings button (mine is the three bars), click on the options gear, choose the content tab, across from the "default font" there is an Advanced button-push that.  On this pop up look until you see a checked box next to "Allow pages to choose their own fonts, instead of my selections above"  UNCHECK this box, then check it again an push OK.  Close the browser and open a new FireFox, type in your herokuapp.com and it should show.  I can use autofill for my herokuapp.com address and it still works.  I have closed and opened FireFox and it still works! :)  YAY!

FOR GOOGLE CHROME 4..  I had to open my herokuapp.com - the google font "Handlee" does not show up.  I when to the three-bar settings in the upper right corner.  Click on "more tools", click "clear browsing data".  Make sure the drop down states "the beginning of time".  MAKE SURE to ONLY check "Cached images and files".  Then click the button at the bottom that states "clear browsing data.  Close Chrome.  Open Chrome and type in your herokuapp.com DO NOT DO AUTOFILL.  Then it shows up for me.  I have to do this every time I want to use Chrome!

I did this on CHROME too:  https://support.google.com/chrome/answer/95290
Text not displaying properly
Check webpage font encoding
If you notice squares showing up in the webpages you visit instead of text, try manually substituting the webpage's encoding. Follow these steps:

Click the Chrome menu Chrome menu on the browser toolbar.
Select Tools.
Select Encoding.
Pick one of the encodings listed or choose 'Auto detect'. If you choose to auto detect, Google Chrome analyzes the content on the page to recommend the most suitable encoding. For the fastest browsing experience, we recommend turning off the auto detect mode after you leave the webpage.

I hope this helps someone else since this has been a HUGE headache for a while now.  

Best Regards.
