### ISSUE TITLE
Feature request: 'remove formatting' button

### ISSUE THREAD

**Issue by courtenay** [daviferreira/medium-editor#505]
This would help in cases where you don't know what the format is to toggle it, or where there's existing block elements (like a PRE) where selecting 'pre' again just nests instead of removing format.

(If there's an easy way to do this, let me know! otherwise I'll probably just implement it myself in a week or three)

**Comment by nmielnik** [comment]
There just so happens to be native support for [this](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) via `document.execCommand('removeFormat', false, true)`.

Because we can leverage `document.execCommand`, this might be as simple as just adding an additional entry into the `ButtonsData` object in `button.js`.

You can see all the existing buttons [here](https://github.com/daviferreira/medium-editor/blob/master/src/js/button.js#L9)

If you add another object into there that looks something like this:
```js
'removeFormat': {
            name: 'removeFormat',
            action: 'removeFormat',
            aria: 'remove formatting',
            contentDefault: '<b>?something?</b>',
            contentFA: '<i class="fa fa-(some-icon)"></i>'
        },
```

I'm not sure if it's possible for the button to be "active" in the toolbar, or if we'd even want it to be.  If we did, you might try setting `useQueryState` to `true` and see if the browser will tell you when a selection has already had its formatting removed..but the more I think about it, the less I think it would be useful.

If you add this in, you should be able to just pass another button name in when you create the MediumEditor instance, and the button should show up:

```js
var editor = new MediumEditor('.editor', {
    buttons: ['bold', 'italic', 'underline', 'removeFormat']
});
```

If you find time to add it, make sure you add some tests! :smile:

**Comment by phiggins42** [comment]
verified that:

```
function RemoveFormat(){
        this.parent = true;
        this.options = {
            name: 'removeFormat',
            action: 'removeFormat',
            aria: 'remove formatting',
            contentDefault: '<b>X</b>',
            contentFA: '<i class="fa fa-eraser"></i>'
        };
        this.name = 'removeFormat';
    }

    return Util.derives(Button, RemoveFormat);
```

creates an extension for this that mostlyworks. does not unlink links. works across multiple paragraphs. removes sup/sub/b/i, does not un-head headings.

**Comment by nmielnik** [comment]
Thanks @phiggins42 for checking that out.

Do you think, based on the behavior you saw, this is worth adding into the codebase?  From the way you describe it, it seems ok that it doesn't unlink links, the header stuff may be a bit annoying though...

**Comment by phiggins42** [comment]
yah, it is a backlog feature request for me too, so going ahead and implementing and adding some tests to see what the end result looks like. above snippet works fine manually adding as extension, but since it is ultimately just a native thing and just a handful of options to define in the existing default button defs it might be worth just supporting (unless the cross-browser support is wonky, and more involved).

headings are block-ish elements, so it isn't really "formatting". I don't mind it not-unwrapping various block nodes (will need to test selection across pre/code/blockquote elements, too), as each of those can be unwrapped individually

**Comment by phiggins42** [comment]
googledocs has this as meta-\, I didn't add that as a key to the definition, but might locally. happy to update branch if is desired there

**Comment by nmielnik** [comment]
This new button is now available in v4.0.3  Thanks @phiggins42 !

**Comment by phiggins42** [comment]
thank you, I just c/p'd your above solution and it worked. I guess I could be thanked for adding the unit test, but then revoke said thanks because I broke CI. NET CHANGE 0 ;)

**Comment by nmielnik** [comment]
Well, if we were able to actually run sauce labs against pull requests from forks, none of this would have happened...instead we have to wait for things to get to master to see if tests pass in all our browsers :disappointed:
