### ISSUE TITLE
expose `paste` as first Extension

### ISSUE THREAD

**Issue by phiggins42** [daviferreira/medium-editor#544]
all of the tooling should be in place already. expose PasteHanlder as the first 'extension', allowing override/replacement/magic-api. 

(paste best candidate because hasn't been released as even a minor bump, and already setup to handle newstyle options, and has never previously been exposed as replaceable, so low back compat risk)

deprecated options:
```
        cleanPastedHTML: [false, "paste.cleanPastedHTML"],
        forcePlainText: [true, "paste.forcePlainText"],
```

Unreleased functionality includes: custom paste regexps, relaying of base options to paste options (which will be simplified by this change?)

disable builtin paste handling:
```
new MediumEditor(".editor", { 
    paste: false
});
```

(paste handling on by default)

forcePlainText: false

```
new MediumEditor(".editor", {
    paste: { forcePlainText: false }
});
```

providing a replace pastehandler:

```
new MediumEditor(".editor", {
     paste: MediumEditor.extensions.paste.extend({
            forcePlainText: false,
            init: function(instance){ /* i can connect and do special things */ }
     })
});
```

note, as a back-compat thing to allow already-instantiated plugins in options passed, the following would "work":

```
new MediumEditor(".editor", {
      extensions:{
            "paste": new MySpecialPasteHandler()
      }
});
```

but the preferred syntax would be:

```
new MediumEditor(".editor", {
    paste: MySpecialPasteHandler
});
```

passing non-default(?) deprecated options would set the default `paste` options for you, and warn about deprecation. this would provide all functionality slated for 4.3 with a warning the options would be removed in 5.0

etc

**Comment by phiggins42** [comment]
cc @nmielnik @daviferreira

**Comment by nmielnik** [comment]
So I think the preferred syntax should remain:

```
new MediumEditor(".editor", { 
    extensions: {
        "paste": new MySpecialPasteHandler()
    }
});
```

For my org, where we have several complex and dependent extensions, being able to instantiate the extensions before passing them in allows us to create our own set of base classes that take in their own set of options to do set themselves up.  We can also keep a reference to these instantiated objects, in places where we might not necessarily want to keep a reference to the medium editor object itself.

Since we have the `init()` method as the method MediumEditor calls to initialize it, if we modify that method to actually take in the `options` for that specific built-in extension, then we can cover all the bases with our existing model, and not necessarily need to have the `{ paste: MySpecialPasteHander }` syntax.

I also value the idea of passing all extensions in via the same `extensions` object, even ones that are overrides. Internally, MediumEditor won't treat them as any special extension (other than creating them if they don't exist and they aren't turned off).  For built-in options, you can have a separate options nested-objects that gets passed into them via the `init()` method.

If we do go with this style, I would definitely be opposed to any plans of deprecating the previous style of passing extensions because of the use cases I mentioned above (There are others who have leveraged the ability to instantiate the extension before passing it into MediumEditor as well). In that case, what are the benefits of supporting this additional syntax beyond syntactic sugar?

**Comment by phiggins42** [comment]
I opted for the syntatic sugar to avoid having to make it verbose as to how to do things like create a simple button tweak ... eg

```
new MediumEditor(".editor", {
      buttons: ["customanchor"],
      customanchor: MediumEditor.Button.extend({
             // i want to change a few of the properties of the button
      });
});
```

instead of 

```
new MediumEditor(".editor", {
    buttons:["customanchor"], 
    extensions: {
        "customanchor": new (MediumEditor.Button.extend({ ... }))
     }
});
```

**Comment by phiggins42** [comment]
the `init` method seems more synonymous with the `startup` (or `setup`?) api of the editor itself. Eg, and "extension" would just need to provide the init method to hook into the lifecycle, _should_ provide a destroy method (or is it activate/deactivate?) ... if you don't _need_ to do anything in the constructor then you shouldn't be required to instantiate something manually imo. 

another thought as to the motivation for syntatic sugar was I couldn't think of a clever way to detect already-instantiated versus passed-as-a-ctor, so making the `extensions:{}` object only accept already instantiated, and instantiating anything passed as a function property to the options (and putting that instantiated thing in `extensions` normalizes the access to `extensions:{}` ...

**Comment by phiggins42** [comment]
release happened, so this is no longer a good candidate for first extension. new paste options in, broke regression. anything to fix will be bandaid. closing this.

**Comment by phiggins42** [comment]
refs #554

**Comment by nmielnik** [comment]
Can you explain why we can't still do the paste handler as an extension, and support the format of options you described here?  I don't think I understand why the backwards compatibility issue I introduced would invalidate the ability to do this, but I definitely could be missing something.

**Comment by phiggins42** [comment]
Because the work I'd done over the last couple weeks was based on the benefit of not having anything already using nested object config params.

**Comment by phiggins42** [comment]
Speaking only to backwards compatibility preservation, I mean.

**Comment by nmielnik** [comment]
You did call out this format of options as being supported with your new schema:

> disable builtin paste handling:
```
new MediumEditor(".editor", { 
    paste: false
});
```
>
> (paste handling on by default)
>
> forcePlainText: false
>
```
new MediumEditor(".editor", {
    paste: { forcePlainText: false }
});
```

Because this seemed to still fit in with one of the formats you mentioned would be supported, I assumed that going forward with this would not impact the ultimate plan.  Was this snippet of code from above intended as an example of something we would NOT support?

**Comment by phiggins42** [comment]
Yes, and it was very easily obtainable (and code-complete) when the deprecation warning path was from config.cleanpastedhtml -> config.paste.cleanhtml ... Now there are two forms of options that need to pass bc ... Config.cleandpastedhtml -> paste.cleanpastedhtml -> paste.cleanhtml ... With the middle example being completely new and adding an additional object depth to something that was already working. Just makes the implementation less elegant IMO, and creates work for me as I was trying to offer a transparent migration path using paste as the first candidate because I'd hoped to come to some agreement on the details with ya'll before the nested-paste options went to release (as per the desc of this ticket). Is moot now. Config.paste is out, and broke bc ... The breakage could have been avoided, the paste handler refactored to not use .options, exposed etc all as outlined above.

**Comment by phiggins42** [comment]
Also apologies, typing from phone, if I sound less coherent/reasonable than normal

**Comment by nmielnik** [comment]
So the only thing the existing changes commit to is the name `cleanPastedHTML` instead of `cleanHTML`, and considering the state of things we could still change it to `cleanHTML` although I don't think this is big of a deal as the rest of the concerns you're describing.  You also still described the option as `paste.cleanPasteHTML` in the beginning of this issue so I'm assuming this isn't the main thing you're driving at.

If we are accepting an object with the paste options inside of it, whether behind the scenes that's explicitly passed as a separate object into the PasteHandler (as it is today) or if we go with merging it into the prototype (as you described here) it won't affect how users pass in the option.  Since PasteHandler isn't supported as 'overridable' today, we still aren't locked in to how options are passed into the PasteHandler itself.  

We could really do just about anything with regards to how we allow the PasteHandler to be overridable, or whether it's an extension, and that will be fine, we won't be breaking anyone.  We'll still want to somehow translate the nested `paste` options into the PasteHandler somehow, and I don't see how anything we've done thus far prevents anything you've proposed?  

I'm guessing there's some "ah-ha" fact/moment that I'm not getting as to why we've restricted anything in regards to making PasteHandler into a modern version extension that is overridable (since neither are true today).  I apologize if I'm being dense and there's something critical I'm not understanding.

**Comment by nmielnik** [comment]
I'm really curious about this because I definitely thought through how I could make these changes in a way that wouldn't disrupt or commit to anything that we would want to change later and I'm worried that I failed in this (this mistake with the camel casing of `cleanPastedHtml` aside)

**Comment by phiggins42** [comment]
It isn't that disruptive, just would have been way easier and elegant to implement the behavior I describe in this ticket without having to consider exsiting nested options. 

> You also still described the option as paste.cleanPasteHTML in the beginning of this issue so I'm assuming this isn't the main thing you're driving at.

right. The was a shorthand from being on phone, but also nudging at the idea that the per-extension props might not need the extra verbosity of referencing the extensions's intent in the method/proptery names. eg: AnchorButton, current option "anchorInputPlaceholder" would become "anchor.inputPlaceholder" ... the same convention change is already inconsistently applied here: https://github.com/phiggins42/medium-editor/blob/refactor/src/js/defaults/deprecated.js in my sweeping change branch.  the actual name of the thing from a->b doesn't matter to me, really. provided it is consistent :)

it may have no implication at all.

**Comment by nmielnik** [comment]
Can we re-open this issue then?  I don't want to give up on this
