### ISSUE TITLE
editableInput event is not present in this.listeners. Nothing happened after subscribing.

### ISSUE THREAD

**Issue by valerykalashnikov** [daviferreira/medium-editor#605]
In the Readme.md file, here https://github.com/daviferreira/medium-editor#capturing-dom-changes
```
var editor = new MediumEditor('.editable');
editor.subscribe('editableInput', function (event, editable) {
    // Do some work
});
```
but in the attachCustomEvent function there is

```
this.setupListener(event);
  // If we don't suppot this custom event, don't do anything
  if (this.listeners[event]) {
       if (!this.customEvents[event]) {
            this.customEvents[event] = [];
        }
        this.customEvents[event].push(handler);
   }
```

but in this.listeners there is no editableInput event, therefore nothing is happened

**Comment by nmielnik** [comment]
The first line in `attachCustomEvent()` is a call to `setupListener(event)`, and if you look at that function, you'll see a case-switch based on the event name.

If 'editableInput' is passed as the event name, it will do the work it needs to in order to attach the event [events.js#223](https://github.com/daviferreira/medium-editor/blob/master/src/js/events.js#L223).

The last part of the case is setting `this.listeners[event]` to true.

We are also doing this exact thing in our test cases ([example](https://github.com/daviferreira/medium-editor/blob/master/spec/events.spec.js#L249)) so it seems pretty unlikely that there's a bug in the event setup code.  

I would double check that the string that you're passing as the event name doesn't contain a typo? Let us know what you find.

**Comment by valerykalashnikov** [comment]
Sorry, guys! It was my mistake, I've download the outdated version of old the fork.

**Comment by nmielnik** [comment]
No problem, let us know if you find anything else.
